DPS-5167: duplicate root HTTP endpoints under jet/
Devolutions/devolutions-gateway pull request #205
Opened 2021-11-19 16:48 UTC by CBenoit

We need to be able to access all important endpoints through `jet/*` to
simplify routing rules.

Older endpoints are still accessibles for compatibility, but will be
removed after one year starting today (2021/11/19).

Note 1: this also fixes DPS-5166 (`jet/health` requiring authorization)

Note 2: `bridge/*` is moved to `jet/bridge/*` without adding compatibility
routes because it's currently unused.

Note 3: `registry/*` is left untouched for now, particular attention is
needed. Since it's not yet used in other products, this shouldn't be an
issue to postpone decision here.

2021-11-25 20:51 UTC, fdubois1 requested changes
Je retirerais seulement 2 commentaires, voir mon explication. Sinon LGTM
Good job !

2021-11-25 20:51 UTC, fdubois1 commented on devolutions-gateway/src/http/controllers/health.rs
> +// TODO: remove legacy controller after 2022/11/19
On devrait retirer ces commentaires. Effectivement on pourrait retirer ça plus tard, mais il existe la notion de version LTS (Long Term Support) dans DVLS alors on pourrait devoir supporter de vieille version DVLS qui utilise les vieilles routes longtemps.  Bref, le jour que tu veux retirer ça, il faudra s'en parler et valider si ça fait du sens de le retirer. 1 an me semble trop court pour le moment.

2021-11-25 20:51 UTC, fdubois1 commented on devolutions-gateway/src/http/controllers/diagnostics.rs
> +// TODO: remove legacy controller after 2022/11/19
Idem

2021-11-25 21:10 UTC, CBenoit commented on devolutions-gateway/src/http/controllers/health.rs
> +// TODO: remove legacy controller after 2022/11/19
Pas de problème, mais je vais quand même laisser un commentaire pour indiquer que c'est legacy depuis aujourd'hui. Ça te semble bon ?

2021-11-25 21:14 UTC, fdubois1 commented on devolutions-gateway/src/http/controllers/health.rs
> +// TODO: remove legacy controller after 2022/11/19
Aucun problème. Juste ne pas mettre de date. Car si il a une date, le jour qu'on passe cette date, tu vas le retirer et peut-être que DVLS ne sera pas prêt. Aussi bien être prévoyant. Mais tu peux laisser un commentaire comme quoi c'est legacy oui

2021-11-25 21:21 UTC, CBenoit commented on devolutions-gateway/src/http/controllers/health.rs
> +// TODO: remove legacy controller after 2022/11/19
J'ai juste indiqué la date à partir de laquelle on a rendu ça legacy à titre informatif, ce n'est pas une date à laquelle il faut retirer :slightly_smiling_face: 
Les détails, on verra en temps et en heure !

2021-11-26 01:44 UTC, fdubois1 approved these changes
LGTM

2021-11-26 01:44 UTC, merged