SBOM cdxgen
Devolutions/devolutions-gateway pull request #471
Opened 2023-06-16 15:08 UTC by sbaker-devolutions

Uses changes from https://github.com/Devolutions/actions/pull/390
Ran successfully https://github.com/Devolutions/devolutions-gateway/actions/runs/5291385875

2023-06-16 15:20 UTC, Sylfwood requested changes

2023-06-16 15:20 UTC, Sylfwood commented on .github/workflows/package.yml
> +  Generate-SBOM:
```suggestion
  generate-sbom:
```

2023-06-16 15:20 UTC, Sylfwood commented on .github/workflows/package.yml
> +          autocreate: 'true'
Les inputs ont changé dans la V1, ca va briser comme c'est là:
https://github.com/Devolutions/actions/tree/v1/dtrack-upload-sbom

2023-06-16 15:23 UTC, sbaker-devolutions commented on .github/workflows/package.yml
> +          autocreate: 'true'
Reordered pour etre dans le meme ordre que dans la doc aussi

2023-06-16 17:30 UTC, CBenoit commented
@Sylfwood does it looks good to you?

2023-06-20 13:02 UTC, Sylfwood approved these changes

2023-06-20 13:10 UTC, merged