Draft: Try testing CI again
Devolutions/devolutions-gateway pull request #665
Opened 2024-01-24 15:45 UTC by irvingoujAtDevolution

The tests were always running fine on my machine, trying to figure out why it does not work in CI.

2024-01-25 11:51 UTC, CBenoit commented
@irvingoujAtDevolution Do you know what was the problem exactly?

2024-01-25 13:22 UTC, CBenoit commented
Looks like this is not fixing the problem. 4 runs out of 6 are never ending:
![image](https://github.com/Devolutions/devolutions-gateway/assets/3809077/6c1a3008-8bba-45d3-941a-3bf1121d54ff)

2024-01-25 18:12 UTC, irvingoujAtDevolution commented on crates/network-scanner-net/Cargo.toml
> +polling = {git = "https://github.com/irvingoujAtDevolution/polling.git"}
a updated version to polling, allow us to kown weather tcp connection has failed or not.

2024-01-25 18:29 UTC, irvingoujAtDevolution commented
It should really work this time, I have run it locally 100 times, all of them stopped within the time frame.
![image](https://github.com/Devolutions/devolutions-gateway/assets/139169536/9c48b7ea-00e2-4c11-ae78-f320730a46d9)

2024-01-25 19:01 UTC, irvingoujAtDevolution commented on crates/network-scanner-net/Cargo.toml
> +polling = {git = "https://github.com/irvingoujAtDevolution/polling.git"}
waiting to be merged into polling main branch https://github.com/smol-rs/polling/pull/185

2024-01-25 19:06 UTC, irvingoujAtDevolution commented
> @irvingoujAtDevolution It might be the case that the problem is still not solved unfortunately :/ The CI has been running for more than 30 minutes on the windows job.

What? it has a

> @irvingoujAtDevolution It might be the case that the problem is still not solved unfortunately :/ The CI has been running for more than 30 minutes on the windows job.

Sorry I might looked at the wrong place, but it looks like it is passing in 3 seconds
![image](https://github.com/Devolutions/devolutions-gateway/assets/139169536/d813a22f-ef5e-4563-9bcb-d3694f994d69)

2024-01-26 06:42 UTC, CBenoit requested changes
Still very unstable. Also fails on Linux sometimes now.

![image](https://github.com/Devolutions/devolutions-gateway/assets/3809077/b1e1b3c9-bad6-4180-95ae-f378eaf833ed)

2024-01-26 21:35 UTC, irvingoujAtDevolution commented
I offcially temproryily give up on fixing the test, I can have about 10% the chance fail the tests tracing_subscriber turned off, 0% if I have the tracing_subscriber turned on. 

I am confident that it will work fine with tcp, see intense_tcp.rs

I added ignore test for all the tests for now, will turn back and fix it in the future.

The improvement I obtained alone the way is good, now the async runtime drop correctly,  The first event information after calling add is registered correctly, the tcp connection established or fails correctly.

@CBenoit Thank you very much for the help, I'll try figure it out later

2024-01-29 03:22 UTC, irvingoujAtDevolution commented on crates/network-scanner-net/Cargo.toml
> +polling = {git = "https://github.com/irvingoujAtDevolution/polling.git"}
It is merged, I will update it once they publish a new version

2024-01-30 07:45 UTC, CBenoit commented
Sorry, I reviewed the code in the other PR: https://github.com/Devolutions/devolutions-gateway/pull/637
Ideally make sure the base is properly set to the branch it is based on and keep the draft status.

2024-01-31 17:56 UTC, irvingoujAtDevolution commented
> Sorry, I reviewed the code in the other PR: #637 Ideally make sure the base is properly set to the branch it is based on and keep the draft status.

Updated according to the reviews

2024-02-01 13:48 UTC, CBenoit commented
I updated to point on a commit from the official polling repo, it’s less likely to break in the future.

2024-02-01 13:49 UTC, CBenoit approved these changes
Thank you!

2024-02-01 14:03 UTC, merged